import '@servicenow/sdk/global'
import { Record } from '@servicenow/sdk/core'

Record({
    $id: 'commission_plan_open_hierarchy_action',
    table: 'sys_ui_action',
    data: {
        name: 'Open Plan Hierarchy',
        action_name: 'x_823178_commissio_open_plan_hierarchy',
        table: 'x_823178_commissio_commission_plans',
        active: true,
        order: 200,
        form_button: true,
        form_link: true,
        form_context_menu: true,
        client: false,
        condition: 'current.isValidRecord()',
        script: "action.setRedirectURL('/x_823178_commissio_plan_hierarchy.do?sysparm_plan_id=' + current.getUniqueValue());",
        form_action: true,
        form_button_v2: false,
        form_menu_button_v2: false,
        format_for_configurable_workspace: false,
        isolate_script: false,
        list_action: false,
        list_banner_button: false,
        list_button: false,
        list_choice: false,
        list_context_menu: false,
        list_link: false,
        list_save_with_form_button: false,
        show_insert: false,
        show_multiple_update: false,
        show_query: false,
        show_update: false,
        sys_domain: 'global',
        sys_domain_path: '/',
        ui11_compatible: false,
        ui16_compatible: false,
    },
})
